- name: Configure MongoDB
  hosts: all
  become: true
  vars:
    mongo_bind_ip: 0.0.0.0

  tasks:
    - name: Add an apt key by id from a keyserver
      apt_key:
        keyserver: keyserver.ubuntu.com
        id: EA312927
        state: present

    - name: Add specified repository into sources list
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse
        state: present

    - name: Install package
      apt:
        name: mongodb-org
        state: present
        allow_unauthenticated: yes

    - name: Change mongo config file
      template:
        src: templates/mongod.conf.j2
        dest: /etc/mongod.conf
        mode: 0644

    - name: Configure service
      systemd:
        name: mongod
        enabled: yes
